lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, delete_friend, validate_npm, model_to_dict, friend_list, all_friends

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
	url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
	url(r'^all-friends/$', all_friends, name='all-friends'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url='/lab-6/', permanent=True), name='index'),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
	url(r'^lab-7/', include(lab_7, namespace='lab-7')),
	url(r'^lab-8/', include(lab_8, namespace='lab-8')),
	url(r'^lab-9/', include(lab_9, namespace='lab-9')),
	url(r'^lab-10/', include(lab_10, namespace='lab-10')),

]

lab_7/models.py
from django.db import models

class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)
	added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
	# Page halaman menampilkan list mahasiswa yang ada
	# TODO berikan akses token dari backend dengan menggunakaan helper yang ada
	mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
	page = request.GET.get('page', 1)
	paginator = Paginator(mahasiswa_list, 20)
	try:
		mahasiswa = paginator.page(page)
	except PageNotAnInteger:
		mahasiswa = paginator.page(1)
	except EmptyPage:
		mahasiswa = paginator.page(paginator.num_pages)
	response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list, "paginator": paginator}
	html = 'lab_7/lab_7.html'
	return render(request, html, response)



    

def friend_list(request):
	friend_list = Friend.objects.all()
	response['friend_list'] = friend_list
	html = 'lab_7/daftar_teman.html'
	return render(request, html, response)

def all_friends(request):
	if request.method == 'GET':
		friend_list = Friend.objects.all()
		data = serializers.serialize('json', friend_list)
		return HttpResponse(data)


@csrf_exempt
def add_friend(request):
	if request.method == 'POST':
		name = request.POST['name']
		npm = request.POST['npm']
		taken = Friend.objects.filter(npm__iexact=npm).exists()
		if (not taken):
			friend = Friend(friend_name=name, npm=npm)
			friend.save()
		data = model_to_dict(friend)
		return HttpResponse(data)

def delete_friend(request, friend_id):
	Friend.objects.filter(id=friend_id).delete()
	return HttpResponseRedirect('/lab-7/get-friend-list')

@csrf_exempt
def validate_npm(request):
	npm = request.POST.get('npm', None)
	data = {
		'is_taken': Friend.objects.filter(npm__iexact=npm).exists() #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
	}
	return JsonResponse(data)

def model_to_dict(obj):
	data = serializers.serialize('json', [obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" class="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Fasilkom Friends</h2>
                    <div id="friend-list" class="list-group">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            // {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:all-friends" %}',//#URL untuk mendapatkan list teman,
                success: function (friend_list) {
                    console.log(friend_list)
                    var list = JSON.parse(friend_list);
                    // #tampilkan list teman ke halaman
                    // #hint : gunakan fungsi jquery append()
                    if(list.length==0) {
                        var html = '<div class="alert alert-danger text-center">\
                            <strong>Oops!</strong> Tidak ada teman\
                            </div>';
                        $("#friend-list").append(html)
                    }
                    else {
                        $.each(list, function(index, friend) {
                            var button = '<span class="pull-right">'+
                                            '<button type="button" class="btn btn-xs btn-danger"'+
                                            'onClick="deleteFriend('+friend.pk+')">'+
                                                '&times;'+
                                            '</button>'+
                                         '</span>';
                            var detail = '<span class="col-xs-4 col-md-2 pull-right">'+
                                            '<button type="button" class="btn btn-xs btn-default btn-block"'+
                                            'onClick="description('+friend.pk+')">'+
                                                'detail'+
                                            '</button>'+
                                         '</span>';
                            var html = '<a class="list-group-item clearfix">'+
                                        friend.fields.friend_name +
                                        ' (' + friend.fields.npm + ')' + button  + '</a>';
                            $("#friend-list").append(html)
                        });
                    }
                }
            });
        });

        const deleteFriend = function(id) {
           window.open('delete-friend/' + id + '/', '_self');
        }

        
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                        {% endif %} {% if mahasiswa_list.has_other_pages %}
                        <ul class="pagination">
                            {% if mahasiswa_list.has_previous %}
                            <li><a href="{% url 'lab-7:index' %}">&laquo;</a></li>
                            <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&lsaquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&lsaquo;</span></li>
                            {% endif %} 
                            {% for page in mahasiswa_list.paginator.page_range %} 
                                {% if mahasiswa_list.number == page %}
                                    <li class="active"><span>{{ page }} <span class="sr-only">(current)</span></span>
                                    </li>
                                {% else %}
                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                            {% endif %} 
                            {% endfor %} 
                            
                            {% if mahasiswa_list.has_next %}
                            <li><a href="?page={{ mahasiswa_list.next_page_number }}">&rsaquo;</a></li>
                            <li><a href="?page={{ mahasiswa_list.paginator.num_pages }}">&raquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&rsaquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                     
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
                var friendParsed = JSON.parse(friend)
                html = '<a class="list-group-item clearfix">' +
                    friendParsed.friend_name + ' ('+friendParsed.npm +
                    ')</a>';
                $("#friend-list").append(html)
                console.log(friendParsed)

            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
        name = $("#field_name").val()
        npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}